version: '3.8'

services:
  # NextJS 后端服务
  nextjs-backend:
    build:
      context: ../  # 指向父级目录的NextJS项目
      dockerfile: dockerfile
      target: runner
    container_name: cyhj-nextjs-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - ../.env.production
    networks:
      - cyhj-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 微信小程序构建服务
  weapp-builder:
    build:
      context: .
      dockerfile: Dockerfile.weapp
    container_name: cyhj-weapp-builder
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - API_BASE_URL=http://nextjs-backend:3000
    networks:
      - cyhj-network
    depends_on:
      - nextjs-backend
    restart: "no"  # 构建完成后停止

  # Nginx 反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: cyhj-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - cyhj-network
    depends_on:
      - nextjs-backend
    restart: unless-stopped

networks:
  cyhj-network:
    driver: bridge

volumes:
  weapp-dist: 